---
title: ''
author: "Sumiya Ganbaatar"
date: "10/8/2021"
output: pdf_document
---

#Studying relationship between "GDP per capita" and "Coronavirus case fatality rate"

#Our hypothesis is that countries that have a lower GDP per capita have higher coronavirus case fatality rate.


```{r, include=FALSE}
library(mosaic); library(readr); library(ggformula); library(tidyverse);library(purrr); library(lares); library(leaps); library(grid);library(gridExtra);library(cleandata); library(ggplot2)
```



```{r}
#Importing the GDP data
df_gdp <- read.csv("/Users/bayarmaaorsoo/Desktop/DATA106 - Project/gdp-per-capita-worldbank.csv")
#Choosing the year 2020 because that's the latest data
df_gdp1 <- df_gdp %>% filter(Year == 2020)
#Dropping columns "Code" and "Year" as we won't use them.
df_gdp1 <- subset(df_gdp1, select = -c(Code, Year))
#Changing column names 
df_gdp1 <- df_gdp1 %>% rename(Country = Entity, GDP_per_capita = GDP.per.capita..PPP..constant.2017.international...)
str(df_gdp1)
```


```{r}
data_covid <- read_csv("/Users/bayarmaaorsoo/Desktop/DATA106 - Project/owid-covid-data (1).csv")
#Selecting necessary data
data_covid <- data_covid[data_covid$date == '2021-12-02',]
variables <- c('location', 'total_cases', 'total_deaths')
data_covid <- data_covid[variables]
# Creating column fatality rate
data_covid<- data_covid %>% mutate(Fatality_rate = (total_deaths/total_cases)*100)
#Changing a column name
colnames(data_covid)[1] <- "Country"

```



```{r}
#Joining two datatables
data <- inner_join(x= df_gdp1, y = data_covid, by = "Country")

#Dropping country Vanuatu because there are only 6 cases and 1 deaths
data <- subset(data, Country != 'Vanuatu')
```


```{r}
#Importing government effectiveness data
data_gov <- read.csv("/Users/bayarmaaorsoo/Desktop/DATA106 - Project/Goverment effectiveness index.csv")
#Selecting only country name and score
data_gov <- subset(data_gov, select = c(Country.Name, X2020..YR2020.))
#Changing column names
colnames(data_gov) <- c("Country","Gov_index")
#Inner joining with the main data
df <- inner_join(x = data, y = data_gov, by = 'Country')
#Converting data type chr to double 
df$Gov_index <- as.double(df$Gov_index)
```



```{r}
#Importing age data
data_age80 <- read_csv("/Users/bayarmaaorsoo/Desktop/Age_over_80.csv")
#Selecting necessary data
data_age80 <- subset(data_age80, select = c(Country, Value))
#Changing column names
colnames(data_age80) <- c("Country","age80")
#Joining df dataset
df <- inner_join(x= data_age80, y = df, by = "Country")

```
```{r}

ggplot(aes(x = age80, y = (Fatality_rate)), data = df) +geom_point() + geom_smooth(method='lm') + labs(title = "Covid fatality rate and percentage of population age over 80",  x ="Percentage of population age over 80", y = "Coronavirus Fatality Rate") + theme(plot.title = element_text(color="blue", size=14, face="bold.italic"))


ggplot(aes(x = Gov_index, y = (Fatality_rate)), data = df) +geom_point() + geom_smooth(method='lm') + labs(title = "Covid fatality rate and Government Effectiveness Index",  x ="Government effectiveness index", y = "Coronavirus Fatality Rate") + theme(plot.title = element_text(color="blue", size=14, face="bold.italic"))

ggplot(aes(x = GDP_per_capita, y = (Fatality_rate)), data = data) +geom_point() + geom_smooth(method='lm') + labs(title = "Covid fatality rate and GDP per capita",  x ="GDP per capita", y = "Coronavirus Fatality Rate") + theme(plot.title = element_text(color="blue", size=14, face="bold.italic"))

```

```{r}
df <- na.omit(df)
modelfull <-lm(Fatality_rate ~ age80+Gov_index+GDP_per_capita, data= df);summary(modelfull)
```

Variable GDP_per_capita is statistically insignificant to predict fatality rate with variable Value and Gov_index in a model

```{r}
bestmodel <- lm(Fatality_rate ~ age80+Gov_index, data= df);summary(bestmodel)
```











```{r}
#Histogram
summary(df$Fatality_rate)
ggplot(df, aes(x = Fatality_rate))  + geom_histogram()
ggplot(df, aes(x = GDP_per_capita)) + geom_histogram()
ggplot(df, aes(x = Gov_index)) + geom_histogram()
ggplot(df, aes(x = age80)) + geom_histogram()
```


    # Exploratory Data Analysis
    
    
```{r}
str(df)
```


```{r}
ggplot(aes(x = GDP_per_capita, y = (Fatality_rate)), data = df) +geom_point() + geom_smooth(method='lm')
ggplot(aes(x = Gov_index, y = (Fatality_rate)), data = df) +geom_point() + geom_smooth(method='lm')
ggplot(aes(x = age80, y = (Fatality_rate)), data = df) +geom_point() + geom_smooth(method='lm')

#Scatterplots with logs
ggplot(aes(x = GDP_per_capita, y = log(Fatality_rate)), data = df) +geom_point() + geom_smooth(method='lm')
ggplot(aes(x = Gov_index, y = log(Fatality_rate)), data = df) +geom_point() + geom_smooth(method='lm')
```


```{r}
#Cleaning data
df <- df[df$Fatality_rate != 0,]
#Removing null values
df <- df[complete.cases(df$Fatality_rate),]
```

```{r}
#Fitting models
model1 <- lm(log(Fatality_rate)~GDP_per_capita, data = df); summary(model1)
model2 <- lm(log(Fatality_rate)~Gov_index, data = df); summary(model2)
model3 <- lm(log(Fatality_rate)~Gov_index+GDP_per_capita, data = df); summary(model3)

plot(model2)
df[df['Fatality_rate']>4,]
```


```{r}
modellog <- lm(log(Fatality_rate)~age80+Gov_index+GDP_per_capita, data = df); summary(modellog)
corr(df)
```

```{r}
data_control2 <- trainControl(method = "LOOCV") # Use Leave One Out.
train(log(Fatality_rate) ~ age80+Gov_index+GDP_per_capita,
      data = df,
      trControl = data_control2,
      method = "lm",
      na.action = na.pass)

data_control2 <- trainControl(method = "LOOCV") # Use Leave One Out.
train((Fatality_rate) ~ age80+Gov_index+GDP_per_capita,
      data = df,
      trControl = data_control2,
      method = "lm",
      na.action = na.pass)

```

```{r}
summary(modellog)
```


```{r}
gdpmodel <- lm(log(Fatality_rate)~GDP_per_capita, data = df); summary(gdpmodel)
govmodel <- lm(log(Fatality_rate)~Gov_index, data = df); summary(govmodel)
agemodel <- lm((Fatality_rate)~age80, data = df); summary(agemodel)
```

